definitions:
  dto.CreateCityReq:
    properties:
      countryId:
        type: integer
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - countryId
    - name
    type: object
  dto.CreateUpdateCountryReq:
    properties:
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  dto.UpdateCityReq:
    properties:
      countryId:
        type: integer
      name:
        maxLength: 20
        minLength: 3
        type: string
    type: object
  dto.UpdateFileRequest:
    properties:
      description:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/cities/:
    delete:
      consumes:
      - application/json
      description: delete city
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: delete city
      tags:
      - City
    post:
      consumes:
      - application/json
      description: Create new city
      parameters:
      - description: CreateCityReq
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCityReq'
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Create new city
      tags:
      - City
    put:
      consumes:
      - application/json
      description: Update city
      parameters:
      - description: UpdateCityReq
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateCityReq'
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Update city
      tags:
      - City
  /v1/cities/{id}:
    get:
      consumes:
      - application/json
      description: Get a city
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Get a city
      tags:
      - City
  /v1/countries/:
    post:
      consumes:
      - application/json
      description: Create new country
      parameters:
      - description: CreateUpdateCountryReq
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUpdateCountryReq'
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Create new country
      tags:
      - Country
  /v1/countries/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Delete a country
      tags:
      - Country
    get:
      consumes:
      - application/json
      description: Get a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Get a country
      tags:
      - Country
    put:
      consumes:
      - application/json
      description: Update country
      parameters:
      - description: CreateUpdateCountryReq
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUpdateCountryReq'
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Update country
      tags:
      - Country
  /v1/files/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create a file
      parameters:
      - in: formData
        name: description
        required: true
        type: string
      - description: Create a file
        in: formData
        name: file
        required: true
        type: file
      responses: {}
      security:
      - AuthBearer: []
      summary: Create a file
      tags:
      - Files
  /v1/files/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a file
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      security:
      - AuthBearer: []
      summary: Delete a file
      tags:
      - Files
    get:
      consumes:
      - application/json
      description: Get a file
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      security:
      - AuthBearer: []
      summary: Get a file
      tags:
      - Files
    put:
      consumes:
      - application/json
      description: Update a file
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: Update a file
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateFileRequest'
      responses: {}
      security:
      - AuthBearer: []
      summary: Update a file
      tags:
      - Files
  /v1/users/login-by-username:
    post:
      consumes:
      - application/json
      description: Login user by userName
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses: {}
      summary: Login user by userName
      tags:
      - Users
  /v1/users/register-by-username:
    post:
      consumes:
      - application/json
      description: Registe user by userName
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses: {}
      summary: Registe user by userName
      tags:
      - Users
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: Send otp to user
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses: {}
      summary: Send otp to user
      tags:
      - Users
securityDefinitions:
  AuthBearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
