definitions:
  dto.CreateUpdateCountryReq:
    properties:
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /v1/countries/:
    post:
      consumes:
      - application/json
      description: Create new country
      parameters:
      - description: CreateUpdateCountryReq
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUpdateCountryReq'
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Create new country
      tags:
      - Country
  /v1/countries/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Delete a country
      tags:
      - Country
    get:
      consumes:
      - application/json
      description: Get a country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Get a country
      tags:
      - Country
    put:
      consumes:
      - application/json
      description: Update country
      parameters:
      - description: CreateUpdateCountryReq
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUpdateCountryReq'
      produces:
      - application/json
      responses: {}
      security:
      - AuthBearer: []
      summary: Update country
      tags:
      - Country
  /v1/users/login-by-username:
    post:
      consumes:
      - application/json
      description: Login user by userName
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses: {}
      summary: Login user by userName
      tags:
      - Users
  /v1/users/register-by-username:
    post:
      consumes:
      - application/json
      description: Registe user by userName
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses: {}
      summary: Registe user by userName
      tags:
      - Users
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: Send otp to user
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.GetOtpRequest'
      produces:
      - application/json
      responses: {}
      summary: Send otp to user
      tags:
      - Users
securityDefinitions:
  AuthBearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
